version: "3.8"

services:
  ollama:
    image: docker.io/ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_KEEP_ALIVE=24h
    restart: always

  bot:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: telegram-bot
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - OLLAMA_API_URL=http://ollama:11434/api/chat
      - MODEL_NAME=${MODEL_NAME}
    depends_on:
      - ollama
    restart: on-failure

volumes:
  ollama-data:
