version: "3.8"

services:
  ollama:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    container_name: ollama
    ports:
      - "11434:11434"    # public API → nginx → Ollama
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped

  webui:
    image: ghcr.io/open-webui/open-webui:git-09a81eb
    expose:
      - 8080/tcp
    ports:
      - "8080:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - open-webui-data:/app/backend/data
    depends_on:
      - ollama

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: telegram-bot
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - OLLAMA_API_URL=http://ollama:11434
      - MODEL_NAME=${MODEL_NAME}
    depends_on:
      - ollama
    restart: on-failure

volumes:
  ollama-data:
  open-webui-data:
